name: Base

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Use shallow clone for faster checkout

      - name: Check broken links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Get Flutter version by FVM
        uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action
        with:
          path: ".fvmrc"

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          architecture: x64
          cache: true

      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze static code
        run: flutter analyze
      # - name: Run tests
      #   run: flutter test
      - name: Check publish warnings
        run: dart pub publish --dry-run
      - name: Build example
        run: |
          cd example
          flutter build appbundle --debug
          flutter build ios --debug --no-codesign
          flutter build web

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: coverage/lcov.info
      #     flags: unittests
      #     name: form_builder_image_picker

  deployment:
    permissions:
      id-token: write
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/deployment.yaml@main
    if: ${{ github.ref_type == 'tag' }}
    needs: build
